services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: n8n start
    envVars:
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-fwbg.onrender.com
      - key: N8N_HOST
        value: n8n-fwbg.onrender.com
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: VUE_APP_URL_BASE_API
        value: https://n8n-fwbg.onrender.com
